### ISSUE TITLE
Add Cake Add to Website

### ISSUE THREAD

**Issue by gep13** [SharpeRAD/Cake.AWS.Lambda#2]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by Jericho** [comment]
The YAML file for this addin was added to the Cake website by the AddinDiscoverer in [June 2019](https://github.com/cake-build/website/blob/master/addins/Cake.AWS.Lambda.yml). I think it's safe to close this issue.

**Comment by gep13** [comment]
@jericho thanks for following up with this!
